apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: helloworld
  namespace: argocd
spec: 
  destination: 
    namespace: helloworld
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: helloworld
    repoURL: "https://github.com/nopponcha/argocd-example-apps.git"
    targetRevision: master
  syncPolicy:
    syncOptions:
      - CreateNamespace=true