apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
spec:
  replicas: 1
  # revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - image: docker.io/noppon/hello-world:1.0.0-1
        name: helloworld
      imagePullSecrets:
      - name: my-registry-secret
