apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: noppon/hello-world:1.0.0-2
        name: guestbook-ui
      imagePullSecrets:
        - name: my-registry-secret
        ports:
        - containerPort: 80
