apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworldnodejs
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: helloworldnodejs
  template:
    metadata:
      labels:
        app: helloworldnodejs
    spec:
      containers:
      - image: docker.io/noppon/hello-world-nodejs:1.0.0-1
        name: helloworldnodejs
      imagePullSecrets:
      - name: my-registry-secret
        ports:
        - containerPort: 80
