apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-nodejs
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: hello-world-nodejs
  template:
    metadata:
      labels:
        app: hello-world-nodejs
    spec:
      containers:
      - image: docker.io/noppon/hello-world-nodejs:1.0.0-1
        name: hello-world-nodejs
      imagePullSecrets:
      - name: my-registry-secret
        ports:
        - containerPort: 80
